[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyBacktest"
version = "0.0.1"
description = "A backtesting framework for stock price prediction strategies"
authors = [
    { name = "Ben Bell", email = "slow111poke@gmail.com" }
]
dependencies = [
    "pandas",
    "numpy"
]
